name: Generate Snake Animation

on:
  # Executa automaticamente a cada 6 horas
  schedule:
    - cron: "0 */6 * * *"
  
  # Permite executar manualmente
  workflow_dispatch:
  
  # Executa quando há push na branch main
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # Checkout do repositório
      - name: Checkout
        uses: actions/checkout@v3
      
      # Gera a animação da cobra
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: VictorOlivei
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # Faz o push da animação gerada para a branch output
      - name: Push Snake Animation
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
